import React, { useState, useEffect, useRef } from 'react';
import { HomeIcon, TrendsIcon, ForecastIcon, ProfileIcon, SettingsIcon, HelpIcon, ShieldIcon, ChatIcon } from '../components/icons/IconDefs';

const Help: React.FC = () => {
  const [activeSection, setActiveSection] = useState('dashboard');
  const sectionRefs = useRef<Record<string, HTMLElement | null>>({});
  const mainContentRef = useRef<HTMLElement>(null);

  const helpSections = [
    {
      id: 'dashboard',
      title: 'Dashboard (Home)',
      icon: <HomeIcon />,
      content: (
        <>
          <p>This is your personalized command center for news. The feed is curated by an AI that learns from the topics you follow and the articles you read, ensuring the content is always relevant to you.</p>
          <p>Each article card is packed with information at a glance:</p>
          <ul>
            <li><strong>AI Summary:</strong> A concise summary generated by AI to give you the key takeaways without the fluff.</li>
            <li><strong>Trust Score:</strong> Our proprietary score (e.g., A+, B, C-) analyzes the source's reputation, journalistic standards, and fact-checking history to give you a quick measure of reliability.</li>
            <li><strong>Sentiment:</strong> Indicates the overall tone of the article (Positive, Negative, Neutral) to help you understand the author's perspective.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'trends',
      title: 'Trends',
      icon: <TrendsIcon />,
      content: (
        <>
          <p>Stay ahead of the curve by exploring what's gaining momentum globally. The Trends page visualizes the most talked-about topics, showing you the volume of coverage for each.</p>
          <p>Clicking on a topic card will take you to a dedicated page with all related articles, allowing you to immerse yourself in the subjects that matter most right now.</p>
        </>
      ),
    },
    {
      id: 'deep-dive',
      title: 'Deep Dive',
      icon: <ShieldIcon className="w-5 h-5 text-slate-400" />,
      content: (
        <>
          <p>Go beyond the surface with our comprehensive analysis tools. The Deep Dive page deconstructs a single article to give you a 360-degree view.</p>
          <ul>
            <li><strong>Bias & Sentiment:</strong> We visualize the source's political leaning on a spectrum and provide a detailed breakdown of the article's sentiment.</li>
            <li><strong>Key Entities:</strong> The AI identifies and tags important people, organizations, and topics mentioned, helping you grasp the core subjects of the article.</li>
            <li><strong>Alternative Perspectives:</strong> To combat echo chambers, we show you how the same story is being covered by sources across the political spectrum, from left to right.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'trust-score',
      title: 'Understanding the Trust Score',
      icon: <ShieldIcon className="w-5 h-5 text-slate-400" />,
      content: (
        <>
          <p>The Trust Score provides an at-a-glance assessment of a news source's reliability and journalistic integrity. It's calculated using an AI model that analyzes multiple factors:</p>
          <ul>
            <li><strong>Historical Accuracy:</strong> The source's track record for factual reporting.</li>
            <li><strong>Journalistic Standards:</strong> Adherence to principles like sourcing, objectivity, and clear separation between news and opinion.</li>
            <li><strong>Ownership & Funding:</strong> Transparency regarding potential influences or conflicts of interest.</li>
            <li><strong>Public Corrections:</strong> Willingness to acknowledge and correct errors.</li>
          </ul>
          <h4 className="font-bold text-white mt-4 mb-2">Score Breakdown:</h4>
          <dl className="space-y-2">
            <dt><strong className="text-green-400">A+ to A- (High Trust):</strong></dt>
            <dd className="pl-4 text-slate-400 border-l-2 border-green-400">Sources with a long history of high-quality, fact-based journalism. They consistently cite multiple sources and issue prompt corrections.</dd>
            <dt><strong className="text-yellow-400">B+ to B- (Medium Trust):</strong></dt>
            <dd className="pl-4 text-slate-400 border-l-2 border-yellow-400">Generally reliable sources that may occasionally show partisan leanings or rely on anonymous sources. Fact-checking is recommended for sensitive topics.</dd>
            <dt><strong className="text-red-400">C+ and Below (Low Trust):</strong></dt>
            <dd className="pl-4 text-slate-400 border-l-2 border-red-400">Sources that frequently mix opinion with reporting, have a clear political agenda, or a poor track record on accuracy. Information should be verified with other sources.</dd>
          </dl>
        </>
      ),
    },
     {
      id: 'forecasts',
      title: 'Forecasts',
      icon: <ForecastIcon />,
      content: (
        <>
          <p>Understand the potential ripple effects of major news events. The Forecasts feature uses predictive AI to model potential short-term and medium-term outcomes of significant global events.</p>
          <p>You can explore the key data points ("Key Drivers") that inform these predictions and use the "What-If" scenario tool to see how the forecast might change based on hypothetical events, like a new trade agreement being signed.</p>
        </>
      ),
    },
    {
      id: 'assistant',
      title: 'NewsBot Assistant',
      icon: <ChatIcon />,
      content: (
        <>
          <p>Your personal AI research assistant is always available via the chat icon in the bottom-right of your screen. Use it to perform powerful actions with simple commands.</p>
          <p>You can ask it complex questions, request summaries of specific topics, or paste a URL from any website to get an instant, unbiased analysis. For example:</p>
          <ul>
            <li>"Explain the impact of the new AI regulation on the tech industry."</li>
            <li>"Summarize the latest developments in sustainable aviation."</li>
            <li>"Analyze this article for bias: [paste URL here]"</li>
          </ul>
        </>
      ),
    },
    {
      id: 'profile',
      title: 'Profile',
      icon: <ProfileIcon />,
      content: (
        <>
         <p>This is your personal space within the app. Here you can view your reading activity and manage your interests.</p>
         <p>By curating your "Followed Topics," you directly influence the AI that powers your "For You" feed on the Dashboard. The more tailored your topics are, the more relevant your news feed becomes.</p>
        </>
       ),
    },
    {
      id: 'settings',
      title: 'Settings',
      icon: <SettingsIcon />,
      content: (
        <>
          <p>Tailor the app to your preferences. The Settings page gives you granular control over your account, notifications, and the app's appearance.</p>
          <ul>
            <li><strong>Account:</strong> Update your email, change your password, or manage your subscription.</li>
            <li><strong>Notifications:</strong> Decide exactly how and when you want to be updated, from breaking news alerts to weekly summaries.</li>
            <li><strong>Appearance:</strong> Switch between visual themes like Dark and Light mode to suit your viewing environment.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'faq',
      title: 'Frequently Asked Questions',
      icon: <HelpIcon />,
      content: (
        <>
          <strong>How is the Trust Score calculated?</strong>
          <p>The Trust Score is generated by an algorithm that considers multiple factors, including the publisher's historical accuracy, adherence to journalistic standards, number of corrections issued, and ratings from independent fact-checking organizations.</p>
          <strong>Is my data and reading history private?</strong>
          <p>Yes. Your privacy is a top priority. Your reading history is used solely to personalize your content feed and is never shared with third parties. All user data is anonymized and encrypted.</p>
          <strong>Can I suggest a new feature or news source?</strong>
          <p>Absolutely! We are always looking to improve. You can submit feedback and suggestions through the "Feedback" link in the Settings page.</p>
        </>
      ),
    },
  ];

  useEffect(() => {
    const observerOptions = {
      root: mainContentRef.current,
      rootMargin: '-20% 0px -80% 0px',
      threshold: 0,
    };

    const observerCallback = (entries: IntersectionObserverEntry[]) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          setActiveSection(entry.target.id);
        }
      });
    };

    const observer = new IntersectionObserver(observerCallback, observerOptions);
    // Fix: Explicitly cast the result of Object.values to fix type inference issues where 'section' was being treated as 'unknown'.
    const sections = Object.values(sectionRefs.current) as (HTMLElement | null)[];

    sections.forEach(section => {
      if (section) observer.observe(section);
    });

    return () => {
      sections.forEach(section => {
        if (section) observer.unobserve(section);
      });
    };
  }, []);

  const handleNavClick = (id: string) => {
    sectionRefs.current[id]?.scrollIntoView({
      behavior: 'smooth',
      block: 'start',
    });
  };

  return (
    <div className="flex h-screen overflow-hidden p-8">
      <div className="flex-1 flex gap-12">
        {/* Left Navigation */}
        <aside className="w-1/4 flex-shrink-0">
          <div className="sticky top-8">
            <h1 className="text-3xl font-bold text-white mb-2">Help & Support</h1>
            <p className="text-slate-400 mb-8">Your guide to NewsBot AI.</p>
            <nav className="flex flex-col space-y-2">
              {helpSections.map(section => {
                const isActive = activeSection === section.id;
                return (
                  <button
                    key={section.id}
                    onClick={() => handleNavClick(section.id)}
                    className={`flex items-center space-x-3 p-3 rounded-lg text-left transition-colors duration-200 ${isActive ? 'bg-slate-700 text-[#64FFDA]' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}
                  >
                    {React.cloneElement(section.icon, { className: `w-5 h-5 ${isActive ? 'text-[#64FFDA]' : 'text-slate-400'}` })}
                    <span className="font-semibold">{section.title}</span>
                  </button>
                );
              })}
            </nav>
          </div>
        </aside>

        {/* Right Content */}
        <main ref={mainContentRef} className="flex-1 overflow-y-auto scroll-smooth">
          {helpSections.map(section => (
            <section
              key={section.id}
              id={section.id}
              ref={(el) => { if(el) sectionRefs.current[section.id] = el; }}
              className="mb-12 scroll-mt-8"
            >
              <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-6">
                 <h2 className="flex items-center space-x-3 text-2xl font-bold text-white mb-4">
                    {React.cloneElement(section.icon, { className: 'w-7 h-7 text-[#64FFDA]' })}
                    <span>{section.title}</span>
                </h2>
                 <div className="prose prose-invert max-w-none text-slate-300 space-y-4">
                    {section.content}
                 </div>
              </div>
            </section>
          ))}
        </main>
      </div>
    </div>
  );
};

export default Help;
